services:
  metamodels.attribute_translatedcombinedvalues.listeners.get_options:
    class: MetaModels\AttributeTranslatedCombinedValuesBundle\EventListener\GetOptionsListener
    arguments:
      - "@metamodels.factory"
      - "%metamodels.system_columns%"
    tags:
      - {
        name: kernel.event_listener,
        event: 'men-at-work.multi-column-wizard-bundle.get-options',
        method: getOptions
      }

  MetaModels\AttributeTranslatedCombinedValuesBundle\EventListener\SetDefaultValuesAtCheckboxesListener:
    arguments:
      - '@cca.dc-general.scope-matcher'
      - '@metamodels.factory'
      - '@translator'
    tags:
      - name: kernel.event_listener
        event: dc-general.model.validate
        method: onValidateModel
